### ISSUE TITLE
Scenario - Projector rotation 

### ISSUE THREAD

**Issue by NeadApTar** [corentingosselin/ProdigyNightclubWiki#4]
If you write the ID of the projectors, for example, `15,16` - everything works well, if you write a group, everything is also fine, but if you write only one ID, then the projector does not work correctly and the cycle `REVERSE/LOOP` does not work.

<details>
<summary>Rotation</summary>

```yml
dance_1:
  path:
    speed: 10
    targets:
      - "155;178;28;30"
      - "-165;144;41;60"
      - "84;98;40;50"
    mode: LOOP
```
</details>

<details>
<summary>Scenario</summary>

```json
{
  "end": 400,
  "frames": [
    {
      "time": 0,
      "projectorActions": [
        {
          "projectors":"15",
          "rotation": {
            "name":"dance_1"
          }
        },
        {
          "projectors":"16,17",
          "rotation": {
            "name":"dance_2"
          }
        }
      ]
    }
  ]
}
```
</details>

<details>
<summary>Gif</summary>

One ID `15` 
![one_id](https://user-images.githubusercontent.com/34768994/118542878-42c4cc80-b75c-11eb-9730-83c1cbda901c.gif)

Two ID `15,16`
![two_id](https://user-images.githubusercontent.com/34768994/118546657-edd78500-b760-11eb-9c53-a2b763a4f772.gif)
</details>

**Comment by corentingosselin** [comment]
Your rotation dance_1 is invalid, here is an example:

```
test:
  path:
    speed: 20
    targets:
      - "0;-60"
      - "0;60"
  repeat:
    amount: -1
    mode: LOOP
```

The mode must be inside repeat section
Tell me if this issue is fixed after that

**Comment by NeadApTar** [comment]
I used the waves example from the wiki. But as I said, if you use multiple projectors, everything works. Just now I checked that if you make only 2 targets, then everything works with 1 projector.

<details>
<summary>Work with multiple ID or in group mode</summary>

```yml
dance_1:
  path:
    speed: 10
    targets:
      - "155;178;28;30"
      - "-165;144;41;60"
      - "84;98;40;50"
    mode: LOOP
```
</details>
<details>
<summary>Work with one ID</summary>

```yml
dance_1:
  path:
    speed: 10
    targets:
      - "155;178;28;30"
      - "-165;144;41;60"
    mode: LOOP
```
</details>

I can send you map and plugin configuration with these strange bugs :D
